### ISSUE TITLE
clean eval

### ISSUE THREAD

**Issue by elespdn** [CondorCompPhil/falcon#25]
leave only ideal xml

**Comment by elespdn** [comment]
ground truth / ideal XML for chevLyon, lancelot, lucanor are missing, right?
They are needed for eval @Jean-Baptiste-Camps @LucenceIng @elespdn

**Comment by LucenceIng** [comment]
Done for lancelot, see pull request #32

**Comment by elespdn** [comment]
Ok, merged!

**Comment by elespdn** [comment]
Now I done the comparison for Lancelot using eval ... and I only have 15 % accuracy !

**Comment by LucenceIng** [comment]
Really strange, I hope it was only because of the presence of the header

**Comment by elespdn** [comment]
No, it was on the original form .. uff !

**Comment by elespdn** [comment]
But do you have the collation output with our pipeline ? I cannot reproduce it now, some weird error

**Comment by LucenceIng** [comment]
The output was produced by CollateX on the lemmas. I've watched the files, and there are quite big differences  between my two witnesses because of the additions of one of them. So I can have errors for 10 tokens because of one addition. But what is strange is that I didn't have a score that weak when I did the evaluation manually on tables

**Comment by elespdn** [comment]
Yes, that result was obtained comparing the ground truth to the collation on forms, so that's good
